#Locating Restriction Sites
from self_database import DNA_rev_comp
import collections


query_seq = """ATATTATAGTGTTATCCGGTGAGTCGATGATCGGGCCTTTTTCACTATTAAGGGTCTAAA
GCACCTACACCCGGAACCGATACAATTACGAGAGTTGGTAACGGCGTACCTTGGATACTT
GCTTATAACATTGAGGAGTAGCGGTTTCTTGTACGACATTACTGCTATGGTCTATCGACG
ACTAGTCGATGAGAGATGGCATCACGTTGTAGCGTAACTGGGCGGTGCGTTCGGCGGTAA
TGGAGACGACTCAGCCGACCGGGAACATATTACATCAACCACCCGATCCTGCAATGGTAG
CAAAACGATCGGAGGGTTCGCATCGAGCAGGTTATTCTCATACCAACATGACAAGGAAGG
TTGTACTCCGTGGTATACCAGGCAATGGACCTAAATGGGTTTAGTTGTATTTCACCGCAC
CTAGTCACGTTGCAACGTGACAACTATACTGACCTTATGAAACTTGGCAAGGCAAGTTGA
TCATCCTTATCTCATCGCGCTACCAAATCCGATCGACGAGTGTGTGTCCTCTGGAGAAGC
CTCAATTCCCTAGTCTCAAGGATGTGATTCCTCCAACGGAAGGCATCTGTAGCGCCGTGG
TTTTCCGACCCCAAGAAACCATTCTCAAGTCAGGCCATCGCATCAGGGACTGTCGGTTAA
CGGACATCCTCTCGTGGCCACGTTCAAAATCGACACAACACATCCAATCTGTGAGGTCTG
CCGGCTGGTCCACCTCATGGCCATTTGCCTTTGATTAAGCTTTAGAACAGCGGGCGGTGG
TCACCGAAAAGAGCCAGCGTACAGCAGCTATTTCGCCCGGAAAGCCCCTTTTAAATGTGG
TTTATTCTCCAGCATATCTTCGCG
""".replace("\n","")

rc_seq = DNA_rev_comp( query_seq )
n = len(query_seq)

idx_dic = collections.defaultdict( list )
for i in range(len(query_seq)):
    idx_dic[ query_seq[i] ].append( i )

base_map = {'A':'T' , 'C':'G' , 'G':'C' , 'T':"A"}
for tmp_base in idx_dic.keys():
    tmp_idx_1 = idx_dic[ tmp_base ]
    tmp_idx_2 = idx_dic[ base_map[tmp_base] ]
    
    for tmp_1 in tmp_idx_1:
        for tmp_2 in tmp_idx_2:
            if tmp_2 - tmp_1< 3:
                continue
            elif tmp_2 - tmp_1 >= 12:
                break
            else:
                if query_seq[ tmp_1:tmp_2+1] == rc_seq[ n-tmp_2-1: n-tmp_1]:
                    print( tmp_1+1 , tmp_2-tmp_1+1 )